### PR TITLE
Revert inline functions

### PR DESCRIPTION
**Pull request by scheibel**
This speeds up the build time on Ubuntu by over 500%.

### CODE REVIEW

**Comment by scheibel** [comment]
I mean the build time oft depending projects, e.g., globjects.

**Comment by mrzzzrm** [comment]
awwwh yeah! :ship: !!!

**Comment by scheibel** [comment]
...and the comparison of function call duration to GLEW decreased by 12-50%, but this shouldn't be any problem.

**Comment by dommueller** [comment]
Mac OS X Mavericks impressions:
* Building glbinding takes ~8 times longer
* Building globjects takes ~0.29 of the time (341% faster)
* Building gloperate takes ~0.57 of the time (176% faster)
* ./build/comparison is unaffected

**Comment by cgcostume** [comment]
:smile:  [build at drone.io](https://drone.io/github.com/hpicgs/glbinding/36):
```
[ 95%] Building CXX object source/glbinding/CMakeFiles/glbinding.dir/source/gl/functions.cpp.o
Connection to 10.0.3.5 closed by remote host.
Maximum build time exceeded
```

**Comment by cgcostume** [comment]
my times (release - fully optimized - x64 - Visual Studio 2015 Preview)
```
inlined (master):
glbinding 	17 mins 16 secs
globjects	 6 mins 58 secs
gloperate	 1 mins  8 secs

not inlined (pull request):
glbinding 	19 mins	52 secs
globjects	 0 mins 29 secs
gloperate	 0 mins 20 secs
```

only issue there is, the windows binary is now ~17 MiB instead of 2MiB ... do want to add build options to limit the build to specific opengl feature (version)

**Comment by scheibel** [comment]
glLoadGen and other OpenGL bindings supports similar functionality, but they don't want to be deployed for general use.
We can integrate such functionality, but then we have to rethink deployment of glbinding.
Either way, building a static library of glbinding should reduce the final executable since not all functions get linked and the massive glbinding lib doesn't need to be deployed.

**Comment by scheibel** [comment]
So, :shipit: ?

**Comment by cgcostume** [comment]
for static linking, the size issue is irrelevant, yes. So lets do this :ship:. (@willy will add / added design issue #76 for feature based deployment)

**Comment by cgcostume** [comment]
hmm.. what about drone.io ... we should ask for extended plan ... :smile:

**Comment by mrzzzrm** [comment]
What do you think of making inline/non inline a configurable option of the code generation? Development builds of apps using glbinding could use the non inline version for faster development, release builds would use the inlined version for smaller executable size and better performance.

**Comment by scheibel** [comment]
Since this would effectively double the code of the public interface, I think we stick with providing per-feature (e.g., OpenGL 4.5 Core) APIs.

**Comment by mjendruk** [comment]
@mrzzzrm you're welcome :wink:

**Comment by mrzzzrm** [comment]
@scheibel not sure we're talking about the same thing. I'm talking about a command line switch for the generate.py script to either generate the function bodies inside the .h file or the .cpp file. 
So that, effectively, the user gets the choice which flavor of glbinding he wants. I can't see how that would double the code of the public interface?

@mjendruk good man, cheers!

**Comment by scheibel** [comment]
Maybe I should have included this in my previous message:
When switching the actual source code for debug and release, then you either can't compile debug or release without regenerating the whole source and discarding the previous build, or you have to store both generations of code to switch between debug and release more smoothly.
If we don't select the *inline* property by the build type but a normal cmake option, then we would end up with two completely different libraries whose headers and libraries for linking cannot be mixed.
The solution would be to provide always both possible interfaces, one inline and the other pre-compiled, but that would effectively double the source code.

Finallly, when deciding between inline or no inline, we actually decide where the compilation overhead and the object code overhead lies; either in glbinding or in **each** dependent library.

**Comment by mrzzzrm** [comment]
"a normal cmake option, then we would end up with two completely different libraries whose headers and libraries for linking cannot be mixed"

That's what I mean, really. Of course most people won't care and just use the inline-free version. Projects where the inlining makes a difference would have the option to set up a special release version of glbinding.

That's of course under the premise that there is any difference in run time overhead at all. Do we have statistics of render threads with a reasonable ratio of draws/state changes/uploads to support the discussion?

**Pull request merged**
